### PR TITLE
fix: Set GTK IM module to ibus

### PR DESCRIPTION
**Pull request by mmstick**
Part 1 of fixing the emoji ibus shortcut

### CODE REVIEW

**Comment by ids1024** [comment]
https://unix.stackexchange.com/questions/260601/understanding-setting-up-different-input-methods suggests:

```bash
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"
export XMODIFIERS="@im=ibus"
```

So I guess we might want to set those variables too?

**Comment by mmstick** [comment]
Yeah that'd be fine

**Comment by ids1024** [comment]
Though I see those already set that way for some reason.

**Review by jacobgkau — APPROVED** [review]
Together with https://github.com/pop-os/desktop/pull/57, gets the `Ctrl-Shift-E` interface for typing emojis working.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
