### PR TITLE
Add sleep before rfkill unblock bluetooth

### LINKED ISSUE #158: Bluetooth off after waking from suspend 22.04
With bluetooth on, I enable suspend.  After waking from suspend bluetooth is off, I need to turn it back on.  I see the same issue was fixed for 20.04 now it's happening in 22.04 #147.  I'm on a Dell XPS 13 7390.

### PR DESCRIPTION
**Pull request by jravetch**
Fixes #158

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Review by n3m0-22 — COMMENTED** [review]
This is passing testing on `gaze15` `oryp4` and `darp6`, but I was not able to recreate the original issue. I also tested on a framework with deep sleep enabled. I have seen no regressions. This will need further testing on other hardware.

**Comment by jravetch** [comment]
The issue was found in a Dell XPS 13 7390 and XPS 15 9500 both running 22.04.

**Comment by n3m0-22** [comment]
Yes, I am currently looking into getting it tested on Dell hardware as well, but it also needs to be tested and not cause any regression on other hardware including System76. I was just reporting my current findings. Thank you for this contribution.

**Comment by leviport** [comment]
I was able to get access to an XPS 13 9310 for testing. It appears that suspend and resume always results in bluetooth being reactivated as expected without this patch, but adding this patch doesn't cause any regressions on this laptop. If it fixes it on the 7390 and the 9500, and it doesn't cause any regressions, then I think this is good to go. @n3m0-22 feel free to approve if you're happy with it.

**Review by n3m0-22 — APPROVED** [review]

**Pull request merged**
