### PR TITLE
[jammy] chore: configure apt esm hook with diversion

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — COMMENTED** [review]
I would prefer diverting to a new, empty file. This is in case a user wants to edit this file.

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
This is creating two new files:
 - `20apt-esm-hook.conf`
 - `20apt-esm-hook.conf.diverted`

After installing running `sudo apt update` while still working now shows the following:

```
All packages are up to date.
N: Ignoring file '20apt-esm-hook.conf.diverted' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
N: Ignoring '20apt-esm-hook.conf' in directory '/etc/apt/apt.conf.d/' as it is not a regular file
```

If the files are manually deleted and `pop-default-setting` is reinstalled only the file `20apt-esm-hook.conf` is created.

**Comment by mmstick** [comment]
Sounds like we can't use diversions for this if apt will ignore them because they're symbolic links.

**Comment by mmstick** [comment]
https://github.com/pop-os/desktop/pull/113

This would be a better solution since it allows us to eliminate the `ubuntu-advantage-tools` dependency that installs this file.

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
Obsoleted by https://github.com/pop-os/default-settings/pull/169 / https://github.com/pop-os/desktop/pull/113.

**Pull request closed without merging**
