### PR TITLE
Add bluetooth suspend/resume script

### PR DESCRIPTION
**Pull request by jackpot51**
A simple script that just turns off bluetooth when suspending and turns it on when resuming. Could be improved by saving the device state before resume and restoring it.

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Comment by linuxgnuru** [comment]
Tested on lemp9 and suspend / resume works with bluetooth keyboard paired.

**Comment by bflanagin** [comment]
Works on Gaze15  with bluetooth mouse

**Comment by n3m0-22** [comment]
Tested on gaze15, orpy4, and darp6. Tested using a mouse and speaker. Works with power menu, launcher, and closing laptop.

Ran `sudo fwts s3 --s3-min-delay 60 --s3-max-delay 60 --s3-multiple 10` checking each time that paired devices are reconnecting and all tests passed.

[results.log](https://github.com/pop-os/default-settings/files/8854984/results.log)

[bluetooth-suspend.txt](https://github.com/pop-os/default-settings/files/8854981/bluetooth-suspend.txt)

**Review by leviport — APPROVED** [review]
No regressions on Dev One, both with 5.17.5 and 5.18.2. Suspend + bluetooth was fine before, and it's still fine with this update.

**Comment by orangecms** [comment]
Awesome, thank ypu SO MUCH @jackpot51!

This thing really drove me nuts, being hard to track down... :pray:

**Pull request merged**
